install.packages("rpart")
library(rpart)
data(iris)
model <- rpart(Species ~ ., data=iris, method="class")
print(model)
plot(model)
text(model)

install.packages("randomForest")
library(randomForest)
data(iris)
model <- randomForest(Species ~ ., data=iris)
print(model)
predict(model, iris[1:5,])

install.packages("e1071")
library(e1071)
data(iris)
model <- naiveBayes(Species ~ ., data=iris)
print(model)
predict(model, iris[1:5,])

install.packages("neuralnet")
library(neuralnet)
data(iris)
iris$Y <- ifelse(iris$Species=="setosa",1,0)
model <- neuralnet(Y ~ Sepal.Length + Sepal.Width,
 data=iris)
print(model)
plot(model)
